email = "jonathan.beatty@tarasquechess.org"
github = "tarasquechess"
youtube = "UCwzbXF7RA4chqlfpLu740cw"
# twitter = "yourtwitterusername"
# facebook = "TarasqueChess"
# facebookgroup = ""

# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "yourinstagramusername"
# quora = "yourquorausername"
# tumblr = "yourtumblrusername"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "yourmediumusername" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
