#+TITLE: Why a New Chess Organization?
#+DESCRIPTION: 'testing description'
#+DATE: 2021-08-16
#+SLUG: 'background'
#+CATEGORIES[]: philosophy about
#+TAGS:
#+DRAFT: true

* Purpose
There are already hundreds of chess organizations in the United States of
varying sizes. The major question is this: what purpose could a new organization
serve?

Our goal is to modernize the experience of learning chess in an accessible,
community-focused way.

- Providing resources for players, parents, and coaches. Often people are unsure
  of what to do after the rules are learned. No need to learn through trial and
  error: we have been doing this for a long time, and we are happy to share our
  experience.
- Making it possible for individuals and communities to compete against players
  of various levels, allowing for the flow of knowledge between isolated groups.
  This also allows for broader and more diverse social relationships using chess
  as a foundation.
- Assisting existing over-the-board chess organizations by increasing the size
  of the community using the scaling possibilities provided by the Internet. We
  do not see these organizations as competitors; we encourage players to play
  tournaments over the board whenever possible.

* The Grahamwood Method
I joined the chess club at Grahamwood Elementary in kindergarten. Most school
chess clubs are just places to hang out and play games. Not here -- the coach
was a tournament chess player whose son attended the school. The club was broken
up into four sections: Pawn, Knight, Bishop, and Rook. Kids played games against
other members of their group and submitted the results on scraps of paper. The
results of those games, calculated by a macro written in Excel 95[fn:excel],
affected their internal rating. Players at the top of their group were given the
right to challenge players in the next group and were candidates for promotion.

This atmosphere wasn't overly strict. Kids would chat between games or sneak off
to the corner of the cafeteria to play the new Pokemon card game. The Pawns
group was a free-for-all, since half the time the players couldn't agree on
whether the position was checkmate. Some kids were satisfied with knowing how to
play.

Others, though, paid more attention to the lists thumb-tacked to the bulletin
board. The desire to improve grew from the existence of an objective metric of
performance. Kids are given verbal feedback from adults constantly, but at chess
club, feedback came on Thursday afternoons in the form of a list generated by a
machine.

The correction of this early immature competitiveness requires learning
sportsmanship and discipline, which is the primary responsibility of a coach.
The coach does not have to be particularly good at chess, although they should
learn the rules and basic ideas[fn:learning]. When my father took over the chess
club in my third grade year, all of the strongest members of the club could beat
him[fn:incentive]. When I moved to the middle school, I began helping coach at
Grahamwood, where I would stay for another fifteen years.

The program went on to produce very strong players. I captained a state champion
team in 4th, 6th, 8th, 10th, 11th, and 12th grade; even in middle and high
school, the team was almost entirely made up of previous Grahamwood students.
Each year, Grahamwood would win either or both sections at the team state
championship. The White Station High School team, the usual high school for
Grahamwood students, won the high school section for six years in a row from
2008-2013. One year, our teams won all four sections[fn:sections].

As coaches, we cannot take full credit for this. The system we inherited from
the previous coach was kept intact. The kids read books or watch videos and
introduce new ideas into the group, which the others can learn by observation.
While it is advantageous to have a strong chess coach, the perpetual engine of
friendly competition does most of the work.

While we had some success in other schools, there were some difficulties to
exporting the method.

[fn:excel] Grahamwood used this spreadsheet for nearly twenty years. The
replacement was a simplified clone in Google Docs.

[fn:learning] This really is not as hard as most people suspect. When children
learn to play chess, it involves a slow process of bootstrapping brain functions
that have not naturally developed. It is normal for a kindergartener to take a
month or more to understand all of the rules. An adult can reach that stage in
an hour or two.

[fn:incentive] Even with excellent sportsmanship, losing to children at a game
is a great incentive to improve, so this was not true for long.

[fn:sections] Primary, Elementary, Middle School, High School.

* Networking and Scale
The Grahamwood method has two weaknesses: it is local, and it requires a seed
population. Chess club at Grahamwood was two days a week after school. The top
players, who also attended team meetings, could spend hours each week playing
one another. This created players with large amounts of experience playing
against other experienced players.

When this method was transferred to another school, it did not work as well.
Without an experienced population, the only way to teach players was directly.
It takes some time to develop a core capable of self-improvement. While these
schools did produce some competitive players, their strength was often a
function of how many tournaments they could attend -- because at those
tournaments, they had opportunities to play Grahamwood students.

The obvious solution is to have more tournaments. Two problems: first, that
running tournaments is logistically difficult and can be expensive, and second,
that schedule conflicts on weekends are extremely common for today's busy kids.
The most effective solution would be to have chess club meetings on weekdays
with multiple schools in attendance, but this is difficult for parents with jobs
or multiple children.

Everything changed with the 2020 pandemic. Instead of doing lessons in person, I
began giving lessons online. Some players struggled with the switch, but others
thrived in a digital environment; I now have students who are quite strong for
their age even though they may have never moved a piece on a physical board.
Some of them spend hours each week playing chess, solving puzzles, and watching
videos on ChessKid or YouTube[fn:videos]. The switch to mostly online education
during the pandemic has been difficult for many parents, but it has also rapidly
modernized our methods of work and education.

My time as a chess coach has taught me to view each player as part of a broader
network, since no player learns in a vacuum. Just as important (or more
important!) than having a good coach is having a good pool of opponents at each
level, so that players can be challenged at each stage[fn:star]. In this light,
the problem with starting new programs was the lack of consistent network
connections to the older established programs, except for the occasional
tournament.

With traditional methods, this view of the network is simply an abstraction.
However, the Internet is a global network that can host any number of designed
networks, which can turn the metaphor into reality. By combining smaller
networks (school clubs, homeschooling organizations, etc) with multiple
overlapping umbrella networks (for inclusive tournaments, League divisions, or
even entire school districts), the scalability and low cost of the Internet can
be used to implement the Grahamwood method on a much larger scale.

[fn:videos] ChessKid videos are targeted at children and are completely safe to
watch. I am cautious of having kids watch random chess videos on YouTube, as not
all channels are family-friendly. However, some YouTube channels like the Saint
Louis Chess Club are reliably kid-appropriate.

[fn:star] I usually spend a disproportionate amount of time playing games
against the strongest player, especially if there is a large gap between the top
two. Even if the other players never catch the top player (one player won every
single game at Grahamwood for an entire year), the chase improves every other
player in the top group, and these benefits spread across the network.
